version: "3.2"
services:
  mysql:
    restart: always
    image: mysql:${MYSQL_VERSION:-latest}
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
    container_name: mysql
    volumes:
      - ./SQL/:/root/SQL/
